package app4;

import java.util.Scanner;

public class M60 {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("enter your age");
		int age = sc.nextInt();
		if(age <= 0) {
			throw new AgeNegativeException("age should be greater than 0")
		}
		//continuation...........
		//continuation...........
		//continuation...........
		//continuation...........
		//continuation...........
		//continuation...........
		//continuation...........
	}
}
